### ISSUE TITLE
最后一种方法实现下？

### ISSUE THREAD

**Issue by Sopage** [Guolei1130/android_p_no_sdkapi_support#2]
https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/UnsafeAllocator.java

**Comment by Guolei1130** [comment]
国庆实现吧

**Comment by razerdp** [comment]
我有一个初步的实现，确实可以把classloader置空了
https://github.com/razerdp/BasePopup/blob/develop/lib/src/main/java/razerdp/basepopup/PopupReflectionHelper.java

而且也可以反射非公开api（popupwindow的windowmanager）

感谢大佬~

之前还想着采用360的方案，不过就是要引入一个so....


ps：目前有个担忧，据说java要从jdk9开始移除unsafe，虽然目前似乎还没有移除，但这说不定是个隐藏炸弹

**Comment by Guolei1130** [comment]
@razerdp 上有政策，下有对策，放心

**Comment by parcool** [comment]
为啥非要调隐藏api？是不是要干啥坏事？

**Comment by huangjingf** [comment]
> 为啥非要调隐藏api？是不是要干啥坏事？

- -解决产品的特殊需求。
